version: "3.8"
services:
  php-apache-environment:
    container_name: php-apache-mysql
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./:/var/www/html/
    ports:
      - 8081:80

  db:
    container_name: db-mysql
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: MY_DATABASE
      MYSQL_USER: MYSQL_USER
      MYSQL_PASSWORD: MYSQL_PASSWORD
    ports:
      - "9907:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8001:80'
    restart: always
    environment:
      PMA_HOST: db
    depends_on:
      - db